import { ImageResponse } from 'workers-og';
import { getOgFonts } from './fonts';
import { OG_DIMENSIONS } from './config';

/**
 * Renders an OG image from a Satori-compatible HTML string.
 * Standardizes dimensions, fonts, and cache headers across all entry points.
 */
export function renderOgImage(
  html: string,
  options: { cacheControl?: string } = {},
): Response {
  const cacheControl =
    options.cacheControl ?? 'public, max-age=31536000, immutable';

  return new ImageResponse(html, {
    width: OG_DIMENSIONS.width,
    height: OG_DIMENSIONS.height,
    fonts: getOgFonts(),
    format: 'png',
    headers: {
      'cache-control': cacheControl,
      'cdn-cache-control': cacheControl,
    },
  });
}

const PNG_MAGIC = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

/** Sanity check for generated bytes — catches silent Satori render failures. */
export function isValidPng(bytes: Uint8Array): boolean {
  if (bytes.byteLength < 1000) return false;
  for (let i = 0; i < PNG_MAGIC.length; i++) {
    if (bytes[i] !== PNG_MAGIC[i]) return false;
  }
  return true;
}
